parameters:
#    troiswa_public.example.class: Troiswa\PublicBundle\Example

services:
#    troiswa_public.example:
#        class: %troiswa_public.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


     twig.extension.text:
                     class: Twig_Extensions_Extension_Text
                     tags:
                         - { name: twig.extension }




#              ======================services créés===========================

     twig.extension.monmien:
                          class: Troiswa\PublicBundle\Services\Twig\Monmien
                          tags:
                              - { name: twig.extension }


     monservice:
             class: Troiswa\PublicBundle\Services\EmailDecorator\Email
             arguments: [@templating, @mailer]


     preexecute_controller:
         class: Troiswa\PublicBundle\Services\Listener\PreMethodListener
         tags:
             - { name: kernel.event_listener, event: kernel.controller, method: PreMethod }
