<?php

namespace Troiswa\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorRepository extends EntityRepository
{
    public function search($word)
    {
        $reqActor = $this->_em
            ->createQueryBuilder()
            ->select('a')
            ->from(' TroiswaPublicBundle:Actor', 'a')
            ->where('a.nom LIKE :word')
            ->setParameter('word', '%' . $word . '%')
            ->getQuery()
            ->getScalarResult();

        return $reqActor;
    }
}
