<?php

namespace Troiswa\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findFilmsHasCat()
    {
        return $this->_em
            ->createQueryBuilder()
            ->select('f')
            ->from(' TroiswaPublicBundle:Film', 'f')

            ->where('f.categories is not null')

            ->getQuery()
            ->getResult();
    }

}
