<?php

namespace Troiswa\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeanceRepository extends EntityRepository
{
    public function findByFilmAndCp($film_id, $cp)
    {
        return $this->_em
            ->createQueryBuilder()
            ->select('s')
            ->from(' TroiswaPublicBundle:Seance', 's')
            ->join('s.cinema', 'c')
            ->where('s.film = :film_id ')
            ->setParameter('film_id', $film_id)
            ->andWhere('c.cp = :cp')
            ->setParameter('cp', $cp)
            ->getQuery()
            ->getResult();
    }

    public function findByFilm($film_id)
    {
        return $this->_em
            ->createQueryBuilder()
            ->select('s')
            ->from(' TroiswaPublicBundle:Seance', 's')
            ->join('s.cinema', 'c')
            ->where('s.film = :film_id ')
            ->setParameter('film_id', $film_id)
            ->getQuery()
            ->getResult();
    }
}
